# Some Julia Commands

### Rohan L. Fernando

### February 2016

https://github.com/rohanLuigi/WGAKenya

Some useful Julia commands are introduced here in the context of simulating genomic data

### Making a matrix A

In [56]:
A = [2 3
     3 4]

2x2 Array{Int64,2}:
 2  3
 3  4

### Making a matrix B

In [25]:
B = [2 5
     2 3]

2x2 Array{Int64,2}:
 2  5
 2  3

### Matrix addition and subtraction

In [26]:
C = A + B 

2x2 Array{Int64,2}:
 3  7
 5  7

In [27]:
C 

2x2 Array{Int64,2}:
 3  7
 5  7

In [31]:
A - B 

2x2 Array{Int64,2}:
 -1  -3
  1   1

### Multiplying two matrices

In [28]:
A*B

2x2 Array{Int64,2}:
  6  11
 14  27

### Transpose of a matrix

In [29]:
A'

2x2 Array{Int64,2}:
 1  3
 2  4

### Computing A'A

In [58]:
A'A

2x2 Array{Int64,2}:
 13  18
 18  25

In [59]:
5A

2x2 Array{Int64,2}:
 10  15
 15  20

### Matrix inverse

In [64]:
iA = inv(A)

2x2 Array{Float64,2}:
 -4.0   3.0
  3.0  -2.0

In [35]:
iA*A

2x2 Array{Float64,2}:
 1.0          0.0
 2.22045e-16  1.0

In [36]:
round(ans,3)

2x2 Array{Float64,2}:
 1.0  0.0
 0.0  1.0

Note that "ans" contains the result of the previous command

### Solving linear equations:

Consider the system of linear equations:
$$
\mathbf{Ax} = \mathbf{y}
$$
where $\mathbf{A}$ is a matrix of known coefficients, $\mathbf{y}$ is a vector of known values, and $\mathbf{x}$ are the unknowns. 

Consider the system of linear equations:
$$
\mathbf{Ax} = \mathbf{y}
$$
where $\mathbf{A}$ is a matrix of known coefficients, $\mathbf{y}$ is a vector of known values, and $\mathbf{x}$ are the unknowns. 

In [67]:
y = [1; 2.5]
sol = iA*y

2-element Array{Float64,1}:
  3.5
 -2.0

In [69]:
y = [1
     2.5]

2-element Array{Float64,1}:
 1.0
 2.5

### Check solution

In [68]:
[A*sol y]

2x2 Array{Float64,2}:
 1.0  1.0
 2.5  2.5

### Different $\mathbf{y}$

In [40]:
y = [1; 3.5]
x = iA*y
A*x

2-element Array{Float64,1}:
 1.0
 3.5

### More efficient method to obtain solution

In [42]:
x = A\y
A*x

2-element Array{Float64,1}:
 1.0
 3.5

## Julia Packages 
* [List of registered Julia packages](http://pkg.julialang.org) 
* Will use [Distributions Package](http://distributionsjl.readthedocs.org/en) to simulate data. 
* It can be added to your system with the command:

## Simulation of data using Julia



In [ ]:
#Pkg.add("Distributions")

* This needs to be done only once. 

* But, to access the functions in the Distributions package the "using" command has to be invoked as:


In [70]:
using Distributions

## Simulate matrix of ``genotype" covariates

In [84]:
nRows = 10
nCols = 5
dist  = Binomial(2,0.5)
X     = rand(dist,nRows,nCols)

10x5 Array{Int64,2}:
 1  2  0  2  2
 0  1  1  1  0
 1  2  0  0  0
 0  2  1  0  1
 1  1  0  0  1
 1  1  0  1  1
 0  0  1  0  2
 2  0  0  1  0
 0  0  1  0  0
 1  1  2  1  0

In [89]:
rand(Binomial(5,0.1),5,2)

5x2 Array{Int64,2}:
 0  1
 0  0
 0  0
 0  0
 1  0

## Add a column of ones for intercept

### Command to make a column of ones

In [19]:
ones(nRows,1)

10x1 Array{Float64,2}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

### Concatenate two matrices

In [90]:
X = [ones(nRows,1) X]

10x6 Array{Float64,2}:
 1.0  1.0  2.0  0.0  2.0  2.0
 1.0  0.0  1.0  1.0  1.0  0.0
 1.0  1.0  2.0  0.0  0.0  0.0
 1.0  0.0  2.0  1.0  0.0  1.0
 1.0  1.0  1.0  0.0  0.0  1.0
 1.0  1.0  1.0  0.0  1.0  1.0
 1.0  0.0  0.0  1.0  0.0  2.0
 1.0  2.0  0.0  0.0  1.0  0.0
 1.0  0.0  0.0  1.0  0.0  0.0
 1.0  1.0  1.0  2.0  1.0  0.0

## Commands to access elements of a matrix

### Submatrix of X:

In [20]:
X[2:5,3:6]

4x4 Array{Float64,2}:
 1.0  1.0  1.0  1.0
 0.0  2.0  1.0  0.0
 1.0  2.0  1.0  2.0
 2.0  0.0  0.0  2.0

In [44]:
X[:,3]

10-element Array{Float64,1}:
 2.0
 1.0
 0.0
 1.0
 2.0
 1.0
 2.0
 1.0
 0.0
 0.0

In [45]:
X[2,:]

1x6 Array{Float64,2}:
 1.0  0.0  1.0  1.0  1.0  1.0

Get element (i,j) of X

In [22]:
X[3,4]

2.0

In [23]:
X[4,4]

2.0

### Dimensions of X

In [50]:
size(X)

(10,6)

In [51]:
rows = size(X,1)

10

In [52]:
cols = size(X,2)

6

In [53]:
rows,cols = size(X)

(10,6)

In [91]:
rows

10

## Simulate phenotypic values

Want to simulate phenotypic values distributed as:
$$
\mathbf{y} = \mathbf{Xb} + \mathbf{e},
$$
where $\mathbf{X}$ is matrix of observed SNP covariates, $\mathbf{b}$ is a vector of effects that are iid Normal random variables with mean zero and variance 0.25, and $\mathbf{e}$ is a vector of residuals that are iid Normal random variables with mean zero and variance 1.0. 

## Simulate effects from normal distribution

In [49]:
nRowsX, nColsX = size(X)
mean = 0.0
std  = sqrt(0.25)
b = rand(Normal(mean,std),nColsX)

6-element Array{Float64,1}:
 -0.750176 
  0.0918465
 -0.53732  
  0.103782 
 -0.418396 
  1.08038  

## Simulate residuals from normal distribution

In [47]:
resStd = 1.0
e = rand(Normal(0,resStd),nRowsX)

10-element Array{Float64,1}:
  0.37212 
  3.03791 
  1.46006 
  0.412755
 -2.19097 
  0.998633
  1.29006 
 -0.667531
 -1.15894 
 -0.310951

In [48]:
y = X*b + e

10-element Array{Float64,1}:
  1.47243 
  4.56398 
  1.55322 
  2.79998 
  0.44617 
  2.11619 
  2.48272 
  0.536686
  0.378693
 -0.266815

## Function to simulate data


In [1]:
using Distributions
function simDat(nObs,nLoci,bMean,bStd,resStd)
    X = [ones(nObs,1) rand(Binomial(2,0.5),(nObs,nLoci))]
    b = rand(Normal(bMean,bStd),size(X,2))
    y = X*b + rand(Normal(0.0, resStd),nObs)
    return (y,X,b)
end

simDat (generic function with 1 method)

## Use of function simDat to simulate data

In [2]:
nObs     = 10
nLoci    = 5
bMean    = 0.0
bStd     = 0.5
resStd   = 1.0
res = simDat(nObs,nLoci,bMean,bStd,resStd)
y = res[1]
X = res[2]
b = res[3]

6-element Array{Float64,1}:
  0.00874248
 -0.743741  
  0.584259  
  0.71705   
  0.714596  
 -0.290068  